-- CreateEnum
CREATE TYPE "Role" AS ENUM ('USER', 'ADMIN', 'HEAD_OF_DEPARTMENT', 'ORGANIZATION_LEADER');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'USER',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
